### ISSUE TITLE
Since version 0.31 the devices in my omada controller are not working in home assistant

### ISSUE THREAD

**Issue by MiguelTVMS** [zachcheatham/ha-omada#42]
Hello,
Until version 0.30 any device that appears in my devices page in Omada controller appeared as a device in my home assistant. When I installed the new version those devices stopped working. I removed the integration and added it again and the page asking me to set a location for each device is not appearing any more.

I used those devices generate a uptime dashboard. Here is the example of the dashboard yaml I have.

```yaml
type: vertical-stack
title: Devices
cards:
  - type: custom:uptime-card
    entity: device_tracker.maia_closet_gateway
    title_template: Gateway
    icon: mdi:wan
    ok: home
    ko: away
    alias:
      ok: Connected
      ko: Disconected
```

<img width="457" alt="image" src="https://user-images.githubusercontent.com/6669765/185195790-a9b26682-65d3-4f1c-8c2a-9629d078fa71.png">
